const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Ivory Coast",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"

]

const paises = [
    "Afeganistao",
    "africa do Sul",
    "Albania",
    "Alemanha",
    "Andorra",
    "Angola",
    "Antiga e Barbuda",
    "Arabia Saudita",
    "Argelia",
    "Argentina",
    "Armenia",
    "Australia",
    "austria",
    "Azerbaijao",
    "Bahamas",
    "Barbados",
    "Barem",
    "Belgica",
    "Belize",
    "Benim",
    "Bielorrussia",
    "Bolivia",
    "Bosnia e Herzegovina",
    "Botsuana",
    "Brasil",
    "Brunei",
    "Bulgaria",
    "Burquina Faso",
    "Burundi",
    "Butao",
    "Cabo Verde",
    "Camarões",
    "Camboja",
    "Canada",
    "Catar",
    "Cazaquistao",
    "Chade",
    "Chile",
    "China",
    "Chipre",
    "Colômbia",
    "Comores",
    "Coreia do Norte",
    "Coreia do Sul",
    "Cosovo",
    "Costa do Marfim",
    "Costa Rica",
    "Croacia",
    "Cuaite",
    "Cuba",
    "Dinamarca",
    "Dominica",
    "Egito",
    "Emirados arabes Unidos",
    "Equador",
    "Eslovaquia",
    "Eslovenia",
    "Espanha",
    "Palestina",
    "Estados Unidos",
    "Estonia",
    "Etiopia",
    "Fiji",
    "Filipinas",
    "Finlandia",
    "França",
    "Gabao",
    "Gambia",
    "Gana",
    "Georgia",
    "Granada",
    "Grecia",
    "Guatemala",
    "Guiana",
    "Guine",
    "Guine Equatorial",
    "Guine Bissau",
    "Haiti",
    "Honduras",
    "Hungria",
    "Iemen",
    "india",
    "Indonesia",
    "Ira",
    "Iraque",
    "Irlanda",
    "Islandia",
    "Israel",
    "Italia",
    "Jamaica",
    "Japao",
    "Jordania",
    "Lesoto",
    "Letonia",
    "Libano",
    "Liberia",
    "Libia",
    "Lituania",
    "Luxemburgo",
    "Macedonia",
    "Madagascar",
    "Malasia",
    "Malaui",
    "Maldivas",
    "Mali",
    "Malta",
    "Marrocos",
    "Mauricia",
    "Mauritania",
    "Mexico",
    "Mianmar",
    "Micronesia",
    "Mocambique",
    "Moldavia",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Namibia",
    "Nauru",
    "Nepal",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Noruega",
    "Nova Zelandia",
    "Oma",
    "Paises Baixos",
    "Palau",
    "Panama",
    "Papua Nova Guine",
    "Paquistao",
    "Paraguai",
    "Peru",
    "Polonia",
    "Portugal",
    "Quenia",
    "Quirguistao",
    "Quiribati",
    "Reino Unido",
    "Republica Centro Africana",
    "Republica Checa",
    "Republica Democratica do Congo",
    "Republica Dominicana",
    "Romenia",
    "Ruanda",
    "Russia",
    "Salomao",
    "Salvador",
    "Samoa",
    "Santa Lucia",
    "Sao Cristovao e Neves",
    "Sao Marinho",
    "Sao Tome e Principe",
    "Sao Vicente e Granadinas",
    "Seicheles",
    "Senegal",
    "Serra Leoa",
    "Servia",
    "Singapura",
    "Siria",
    "Somalia",
    "Sri Lanca",
    "Suazilandia",
    "Sudao",
    "Sudao do Sul",
    "Suecia",
    "Suiça",
    "Suriname",
    "Tailandia",
    "Tajiquistao",
    "Tanzania",
    "Timor Leste",
    "Togo",
    "Tonga",
    "Trindade e Tobago",
    "Tunisia",
    "Turcomenistao",
    "Turquia",
    "Tuvalu",
    "Ucrania",
    "Uganda",
    "Uruguai",
    "Usbequistao",
    "Vanuatu",
    "Vaticano",
    "Venezuela",
    "Vietna",
    "Zambia",
    "Zimbabue"
]

function countryPicker() {
    return paises[Math.floor(Math.random() * paises.length)].toUpperCase();
}

export { countryPicker };